### ISSUE TITLE
Extracting content inside the bounding boxes

### ISSUE THREAD

**Issue by talalz94** [ag-ds-bubble/swtloc#14]
How can I crop the content inside the bounding boxes of each type? 

I want to use the mask and crop the content on the real image to extract this text.

**Comment by ag-ds-bubble** [comment]
Hello @talalz94 , I am not sure if I got your issue correctly. 

Did you mean how to crop the BBox region? Or that you want to perform OCR and extract the text that lies within that BBox?

Kindly clarify.

**Comment by talalz94** [comment]
Yes, for e.g I will run the SWT algorithm to extract the text from the boxes like the image below:

![image](https://user-images.githubusercontent.com/29313245/150785006-e1f3b48e-ddb9-4f45-983b-d1a13a1a055e.png)

Then I will run the OCR on the individual text fields that are extracted rather than the whole document because OCRs work well for structured lines of texts and not when text fields are randomly placed.

**Comment by ag-ds-bubble** [comment]
Ohh ok, well once you have the coordinates of the BBox you can use any image library such as opencv or PIL to crop that very specific portion of the image, and then send it off to an OCR engine/service for text extraction.

As of now SWTLoc doesn't include cropping function, but once you have your BBox coordinates that won't be that hard to do (just google how to). I may include this feature in the next release 🙂

**Comment by ag-ds-bubble** [comment]
Hello @talalz94 , SWTLoc v2.0.0 now has the `saveCrop` feature which allows you to generate crops of the input image.
In v2.0.0,

For Transforming the input image : 
```python
!pip install swtloc
from swtloc import SWTLocalizer

imgpath = rawimage_path+'issue14/issue14.png' # Image Path
respath = rawimage_path+'issue14/results/' # Results Folder Path
swtl = SWTLocalizer(image_paths=imgpath)
swtImgObj = swtl.swtimages[0]
# Stroke Width Transform
swt_mat = swtImgObj.transformImage(text_mode='lb_df',
                                   minimum_stroke_width=2, maximum_stroke_width=20,
                                   maximum_angle_deviation=np.pi/4,
                                   gaussian_blurr_kernel=(7, 7),
                                   include_edges_in_swt=True)
```
![issue14_01_02_03_04](https://user-images.githubusercontent.com/56403028/154556381-40ef912d-7497-49d4-9bed-3d8062baff63.jpg)

For Localizing Letters : 
```python
# Localize Letters
localized_letters = swtImgObj.localizeLetters(maximum_pixels_per_cc=5_000,
                                                acceptable_aspect_ratio=0.22,
                                                localize_by='min_bbox')
```
![issue14_06_07_11_13](https://user-images.githubusercontent.com/56403028/154557737-b4c3b16a-ac86-4c48-b38c-1dd2c3b19bc2.jpg)

For Localizing Words:
```python
# Localize Words
localized_words = swtImgObj.localizeWords(localize_by='bbox')
```
![issue14_14_15_16](https://user-images.githubusercontent.com/56403028/154557789-4c529187-3517-4213-9d61-fd1356c936b2.jpg)

For Saving Crops:
```python
from swtloc.configs import (IMAGE_SWT_TRANSFORMED,
                            IMAGE_ORIGINAL)

word_iterator = swtImgObj.wordIterator(localize_by='bbox')  # Returns a generator over all the localized words
```
```python
word, _, _ = next(word_iterator)   # Keep iterating over a word to find the word of interest, at every iteration a plot is also shown for that particular word which is returned.
word_label = word.label  # Retrieves the word label
```
```python
swtImgObj.saveCrop(save_path=respath, crop_of='words', crop_key=word_label,
                   crop_on=IMAGE_SWT_TRANSFORMED, crop_type='bubble')
swtImgObj.saveCrop(save_path=respath, crop_of='words', crop_key=word_label,
                   crop_on=IMAGE_ORIGINAL, crop_type='bbox')
```
These are some of the crops so generated :
![issue14_words-8_bbox_IMAGE_ORIGINAL_CROP](https://user-images.githubusercontent.com/56403028/154558435-910c8032-e3f4-40df-83cf-2447f9f5e688.jpg)
![issue14_words-8_bubble_IMAGE_SWT_TRANSFORMED_CROP](https://user-images.githubusercontent.com/56403028/154558456-eb1aac4b-1352-4a8d-b8fa-d12c8ae5b329.jpg)
![issue14_words-32_bbox_IMAGE_ORIGINAL_CROP](https://user-images.githubusercontent.com/56403028/154558499-b712ac9f-678a-4ceb-a84d-5ef7d7cad080.jpg)
![issue14_words-32_bubble_IMAGE_SWT_TRANSFORMED_CROP](https://user-images.githubusercontent.com/56403028/154558504-71c02810-9751-42b5-aaf2-01a22ccea4bf.jpg)
![issue14_words-24_bbox_IMAGE_ORIGINAL_CROP](https://user-images.githubusercontent.com/56403028/154558527-760b91ac-d192-4413-9bd2-789319184a56.jpg)
![issue14_words-24_bubble_IMAGE_SWT_TRANSFORMED_CROP](https://user-images.githubusercontent.com/56403028/154558539-abaf4d4c-d303-496a-a6b2-f3949488be7e.jpg)


For more details on v2.0.0, have a look at : [Usage Notebook](https://github.com/ag-ds-bubble/swtloc/blob/master/examples/SWTloc-Usage-%5Bv2.0.0-onwards%5D.ipynb)

**Comment by ag-ds-bubble** [comment]
With the last comment, I am closing this issue. Feel free to re-open this issue should you stumble upon some other issue :)
