### ISSUE TITLE
Quickly use images already loaded (cv2)

### ISSUE THREAD

**Issue by dariemihai95** [ag-ds-bubble/swtloc#2]
It would be great to use an image that is already loaded for example with opencv

**Why ?**

- skip whole: Use own preprocessing methods -> save image(set cache path) -> load image into swtloc(from cache path) **to** use own preprocessing -> use swtloc

**Benefits**

Avoid unnecessary setup. Avoid use of extra directories. Less code. Maybe faster runtime as it cuts operations.

**Comment by ag-ds-bubble** [comment]
Hey @dariemihai95, This functionality has been built, just waiting for some finalizations, and will be rolled out in the next release. Thanks

**Comment by ag-ds-bubble** [comment]
This functionality is now live in v1.0.0.3  with https://github.com/ag-ds-bubble/swtloc/blob/169d5d7b389c57bcf4f494bbecd6590a99c9770c/swtloc/swtlocalizer.py#L40 function, where the `swttransform` call can accept either imgpaths - a list of str paths for images or an image itself(numpy ndarray).
