### ISSUE TITLE
swtloc fails to run on Ubuntu 21.10

### ISSUE THREAD

**Issue by arbakker** [ag-ds-bubble/swtloc#21]
Hi, I am having issues getting swtloc to work, and due to my lack of knowledge on numba (considering the error message) I am unable to determine whether this is an issue with my setup or if there is something wrong with the pip package itself, therefore opening this issue. 

I  am running Ubuntu 21.10 with Python 3.9.7 and installed `swtloc` with `pip install swtloc` which installed the library without any error messages and installed version `2.1.0` of swtloc:

```sh
$ pip show swtloc                  
Name: swtloc
Version: 2.1.0
...
```

Next I tried running the following script, see also the attached `test.jpg` image. I also tried a few different images and image formats all resulting in the same outcome (ignore the content of the image, I grabbed the first result from an image search):

```python
import swtloc as swt
imgpath = 'test-data/test.jpg
swtl = swt.SWTLocalizer(image_paths=imgpath)
swtImgObj = swtl.swtimages[0]
swt_mat = swtImgObj.transformImage(text_mode='lb_df',
                                   auto_canny_sigma=1.0,
                                   maximum_stroke_width=20)
```

Which returned with an error:

```
Traceback (most recent call last):
  File "/home/$USER/workspace/github.com/arbakker/kook/kook/test-swtloc.py", line 5, in <module>
    swt_mat = swtImgObj.transformImage(text_mode='lb_df',
  File "/home/$USER/.local/lib/python3.9/site-packages/swtloc/abstractions.py", line 573, in transformImage
    self.image_swt = transform_function(edged_image=self.image_edged,
  File "/home/$USER/.local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/$USER/.local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(int32, 2d, C) for 'swt_matrix.2', defined at /home/$USER/.local/lib/python3.9/site-packages/swtloc/core.py (126)

File "../../../../../.local/lib/python3.9/site-packages/swtloc/core.py", line 126:
def swt_strokes(edged_image,
    <source elided>
            _ray_ix = ray_indices[:ray_pointer, 1]
            for each_y, each_x in zip(_ray_iy, _ray_ix):
            ^

During: typing of assignment at /home/$USER/.local/lib/python3.9/site-packages/swtloc/core.py (126)

File "../../../../../.local/lib/python3.9/site-packages/swtloc/core.py", line 126:
def swt_strokes(edged_image,
    <source elided>
            _ray_ix = ray_indices[:ray_pointer, 1]
            for each_y, each_x in zip(_ray_iy, _ray_ix):
            ^
```

Any ideas what might be causing the issue, or suggestion on how to troubleshoot the issue?

![test](https://user-images.githubusercontent.com/3216462/158036691-fc10537c-1167-4df8-8bd1-f1fb7f140073.jpg)

**Comment by ag-ds-bubble** [comment]
Hey, I am not so sure about Ubuntu Platform (as I don't really have access to it), but I tried running it on the following configuration

**Python** (Venv) - 3.9.7
**OS** : Windows 10
**swtloc** version : `2.1.0`

via the following code-block 

```py
from swtloc import SWTLocalizer
from swtloc.configs import (IMAGE_ORIGINAL, 
                            IMAGE_GRAYSCALE,
                            IMAGE_EDGED,
                            IMAGE_SWT_TRANSFORMED,
                            IMAGE_CONNECTED_COMPONENTS_3C,
                            IMAGE_CONNECTED_COMPONENTS_3C_WITH_PRUNED_ELEMENTS,
                            IMAGE_CONNECTED_COMPONENTS_PRUNED_3C,
                            IMAGE_PRUNED_3C_LETTER_LOCALIZATIONS,
                            IMAGE_ORIGINAL_LETTER_LOCALIZATIONS,
                            IMAGE_ORIGINAL_MASKED_LETTER_LOCALIZATIONS,
                            IMAGE_PRUNED_3C_WORD_LOCALIZATIONS,
                            IMAGE_ORIGINAL_WORD_LOCALIZATIONS,
                            IMAGE_ORIGINAL_MASKED_WORD_LOCALIZATIONS)

def save_results(swtimgobj, res_path):
    """Helper Function"""
    savepath1 = swtimgobj.showImage(image_codes=[IMAGE_ORIGINAL, IMAGE_GRAYSCALE, IMAGE_EDGED, IMAGE_SWT_TRANSFORMED],
                                   plot_title='SWT', plot_sup_title=f'\nTransform Time - {swtImgObj.transform_time}',
                                   save_fig=True, save_dir=res_path, dpi=300)

    savepath2 = swtimgobj.showImage(image_codes=[IMAGE_CONNECTED_COMPONENTS_3C,
                                                IMAGE_CONNECTED_COMPONENTS_3C_WITH_PRUNED_ELEMENTS,
                                                IMAGE_PRUNED_3C_LETTER_LOCALIZATIONS,
                                                IMAGE_ORIGINAL_MASKED_LETTER_LOCALIZATIONS],
                                     plot_title='Letter Localizations\n',
                                   plot_sup_title=rf"Localization Method : ${swtimgobj.cfg['swtimage.localizeletters.localize_by']}$",
                                   save_fig=True, save_dir=res_path, dpi=300)

    savepath3 = swtimgobj.showImage(image_codes=[IMAGE_PRUNED_3C_WORD_LOCALIZATIONS,
                                                IMAGE_ORIGINAL_WORD_LOCALIZATIONS,
                                                 IMAGE_ORIGINAL_MASKED_WORD_LOCALIZATIONS],
                                    plot_title='Word Localizations\n',
                                    plot_sup_title=rf"Localization Method : ${swtimgobj.cfg['swtimage.localizewords.localize_by']}$",
                                    save_fig=True, save_dir=res_path, dpi=300)
    
    print('First Result Image : ', savepath1)
    print('Second Result Image : ', savepath2)
    print('Third Result Image : ', savepath3)
    
imgpath = 'issue21/issue21.jpg'
respath = 'issue21/results/'
swtl = SWTLocalizer(image_paths=imgpath)
swtImgObj = swtl.swtimages[0]

# Transformation
swt_mat = swtImgObj.transformImage(text_mode='db_lf',
                                   maximum_stroke_width=50)

letters = swtImgObj.localizeLetters()
words = swtImgObj.localizeWords()

save_results(swtimgobj=swtImgObj, res_path=respath)
```
which gave the following results : 

- For SWT Transformation
![issue21_01_02_03_04](https://user-images.githubusercontent.com/56403028/158079687-cef1e605-2691-4dc7-bd21-79f1f9a6cb55.jpg)

- For Letter Localization
![issue21_06_07_11_13](https://user-images.githubusercontent.com/56403028/158079684-c0132913-d84b-43cc-b99c-97a207302384.jpg)

- For Word Localization
![issue21_14_15_16](https://user-images.githubusercontent.com/56403028/158079681-f159cfca-ccda-40c2-aaf8-74601afce497.jpg)

As for the numba specific error which you are encountering on ubuntu, what i can gather from `Cannot unify array(int64, 2d, C) and array(int32, 2d, C)..` is that typing of the two `zip` elements in `core.py` file has turned to be different. I will try to look into it, but in the mean time could you make the changes to your own code-block as shown below and confirm whether you are able to run or not?

```py
import swtloc as swt
imgpath = 'test-data/test.jpg
swtl = swt.SWTLocalizer(image_paths=imgpath)
swtImgObj = swtl.swtimages[0]
swt_mat = swtImgObj.transformImage(text_mode='db_lf',
                                   engine='python',
                                   maximum_stroke_width=50)
```
Through this code-block (engine='python'), i am getting the same results as shown above, just that `swtImgObj.transform_time` = `0.433 sec` which is nearly 10x worse than engine='numba'. 

Also kindly note, addition of `numba` as an engine(in v2.0.0) was solely to speed up the computationally heavy `for` loop that sits in `core.py` (no other reason..)

**Comment by arbakker** [comment]
Hi, thanks for the extensive answer, really appreciate it. Your adapted code example works for me (with `engine='python',`). Good to know it seem to be an Ubuntu specific issue, running it on Windows is a feasible workaround for me. Considering it only depends on my personal preference :)

**Comment by ag-ds-bubble** [comment]
Good to know :)
From what i can gather is that the [swt_strokes](https://github.com/ag-ds-bubble/swtloc/blob/c395c9e1e01a4040f1879cdcd05713f2f96ec7b2/swtloc/core.py#L9) would require explicit numpy annotation for the dtypes. I will park this for the next minor release.
Thanks for pointing it out.

Closing this issue for now. Kindly reopen should you feel the need to :)
