### ISSUE TITLE
No module named 'swtlocalizer'

### ISSUE THREAD

**Issue by emadyounan** [ag-ds-bubble/swtloc#22]
Good evening,

I'm trying to use this library with python 3.10 but I got error No module named 'swtlocalizer' what should I do?

Thanks

**Comment by mendi80** [comment]
The problem is: "from cv2 import cv2"
Just change to: "import cv2"

**Comment by emadyounan** [comment]
@mendi80 not working

**Comment by mendi80** [comment]
You must change the cv2 import in all swloc package files:
https://github.com/ag-ds-bubble/swtloc/search?q=%22from+cv2+import+cv2%22
And to see the actual error remove the "try...except" in __init__.py file

**Comment by ag-ds-bubble** [comment]
#23 Closing this issue
