### ISSUE TITLE
incorrect cv2 import

### ISSUE THREAD

**Issue by mendi80** [ag-ds-bubble/swtloc#23]
"from cv2 import cv2" cause error.
"import cv2" is the correct way.

**Comment by ag-ds-bubble** [comment]
With #24 this issue stands fixed (swtloc v2.1.1) - with fixed opencv-python imports in all files.
Let me know if the issue still persists.

**Comment by ag-ds-bubble** [comment]
Closing this issue. Feel free to reopen this should the issue persists.

**Comment by ag-ds-bubble** [comment]
Closing this issue for now. Feel free to re-open it should the issue persists.
