### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by aazuspan** [ag-ds-bubble/swtloc#3]
I've been searching for a straightforward library that can generate bounding boxes around text using SWT, so I'm really excited to find this. It looks great! I just noticed a couple little issues in the readme that I thought I'd mention.

In your [example code,](https://github.com/ag-ds-bubble/swtloc#stroke-width-transform) `acceptCC_aspectratio = 5` throws an error because it's expecting a float. Changing it to `5.` works. It might be worth adding `import numpy as np` to the example also, since it's required.

**Comment by ag-ds-bubble** [comment]
Thanks for pointing it out @aazuspan, it has been updated.

**Comment by ag-ds-bubble** [comment]
Closing this issue!
