### ISSUE TITLE
blurr_kernel has no effect

### ISSUE THREAD

**Issue by aazuspan** [ag-ds-bubble/swtloc#4]
# Issue
Changing the `blurr_kernel` param in `SWTLocalizer.swttransform()` has no effect.

# Cause
`SWTLocalizer._image_read()` passes a fixed 5x5 kernel to `cv2.GaussianBlur`, ignoring `blurr_kernel`. 

https://github.com/ag-ds-bubble/swtloc/blob/704fcf3ddcf0e9f15adfe2d3c5ef14c86dee6811/swtloc/swtlocalizer.py#L328

**Comment by ag-ds-bubble** [comment]
Thanks @aazuspan for pointing this out. I am about to release the next version, will definitely fix this.

**Comment by ag-ds-bubble** [comment]
Fixed in the recently released v1.0.0.3!
