### ISSUE TITLE
Grayscale image error in swttransform

### ISSUE THREAD

**Issue by aazuspan** [ag-ds-bubble/swtloc#6]
Being able to load an image directly into `SWTLocalizer.swttransform` is awesome, thanks for adding that. I ran into a small bug with grayscale images.

# Issue
Passing an image loaded using `cv2.imread( ... , cv2.IMREAD_GRAYSCALE)` raises `ValueError: When provinding a singular image through 'image' argument, the value should be np.ndarray with 3 Channels(RGB) or 1 Channel(GrayScale), i.e the output of cv2.imread()`.

# Cause
The `shape` of a grayscale image returned by `cv2.imread()` is (height, width), not (height, width, 1), so it fails the sanity check. 

https://github.com/ag-ds-bubble/swtloc/blob/7dd1014cbade17aafd6b40bfe2ccf9d73ac49ecd/swtloc/swtlocalizer.py#L236

**Comment by ag-ds-bubble** [comment]
Fixed! Thanks for Pointing it out.
